import React from "react";

const Terms = () => {
    return (
        <>
            <h2> Youro Terms of Service
 </h2>

 <div>
<h3><strong>&nbsp;</strong></h3>
<p>BY CLICKING "I AGREE," CHECKING A RELATED BOX TO SIGNIFY YOUR ACCEPTANCE, USING ANY OTHER ACCEPTANCE PROTOCOL PRESENTED THROUGH THE SERVICE (AS DEFINED BELOW), OR OTHERWISE AFFIRMATIVELY ACCEPTING THESE TERMS AND CONDITIONS, YOU ACKNOWLEDGE THAT YOU HAVE READ, ACCEPTED, AND AGREED TO BE BOUND BY THIS AGREEMENT. IF YOU DO NOT AGREE TO THESE TERMS AND CONDITIONS, DO NOT CREATE AN ACCOUNT OR USE THE SERVICE. YOU HEREBY GRANT AGENCY AUTHORITY TO ANY PARTY WHO CLICKS ON THE "I AGREE" BUTTON OR OTHERWISE INDICATES ACCEPTANCE TO THESE TERMS AND CONDITIONS ON YOUR BEHALF.</p>
<p>ARBITRATION NOTICE: UNLESS YOU TIMELY OPT-OUT OF ARBITRATION IN ACCORDANCE WITH THESE TERMS AND CONDITIONS, YOU AGREE THAT DISPUTES BETWEEN YOU AND US OR YOU AND THE MEDICAL GROUPS OR PROVIDERS ARISING OUT OF OR RELATED TO THESE TERMS AND CONDITIONS OR THE SERVICE WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION, AND YOU WAIVE YOUR RIGHTS TO A JURY TRIAL AND TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION, AS FURTHER SET FORTH BELOW. WE EXPLAIN SOME EXCEPTIONS AND HOW YOU CAN OPT OUT OF ARBITRATION BELOW.</p>
<p>IF YOU HAVE A MEDICAL EMERGENCY, SEEK IN-PERSON EMERGENCY CARE IMMEDIATELY OR DIAL 911. THE SERVICE IS NOT APPROPRIATE FOR ALL MEDICAL CONDITIONS OR CONCERNS. THIS AGREEMENT IS SUBJECT TO CHANGE AS PROVIDED HEREIN.</p>
<p>Youro, its affiliates, and/or its subsidiaries (collectively, "Youro," "we," or "us") own and operate the websites, applications, and associated services provided through the Youro platform (collectively, the "Platform"). Your access and use of the Platform, any part thereof, or anything associated therewith, including its content ("Content"), any products or services provided through the Platform or otherwise by Youro, and any affiliated website, software, or application owned or operated by Youro (collectively, including the Platform and the Content, the "Service") are governed by these Terms and Conditions ("Terms and Conditions" or "Agreement").</p>
</div>
<p>Please read this Agreement carefully because it sets forth the important terms you will need to know about the Service. In this Agreement, the terms "you" and "yours" refer to the person using the Service. If you are signing up a family member, the family member must be 18 or older and you are responsible for their compliance with this Agreement. Please see the "Limited Use and Availability" Section of this Agreement for more information regarding the use of the Service and applicable limitations. The Service is not intended for individuals under the age of eighteen (18), and individuals under the age of eighteen (18) are prohibited from using all or any part of the Service or entering into this Agreement, even if a parent or legal guardian would be willing to provide consent to use the Service or this Agreement. Please contact us at support@youro.com if you are a parent or legal guardian of an individual under the age of eighteen (18) who you believe has used the Service without your consent.</p>
<p>&nbsp;</p>
<p><strong>Acceptance of Terms and Conditions</strong></p>
<div>
<p>Your access to and use of the Service is subject to this Agreement, as well as all applicable laws and regulations. If you do not accept and agree to be bound by this Agreement in its entirety, you are strictly prohibited from visiting, accessing, registering with and/or using the Service or any information or Content provided through the Service, except as necessary to review this Agreement. The Service is continually under development, and we reserve the right to revise or remove any part of this Agreement or the Service in our sole discretion at any time and without prior notice to you. Any changes to this Agreement are effective upon posting to the Platform. Unless otherwise indicated, any new Content added to the Service is also subject to this Agreement upon posting to the Platform. If you disagree with this Agreement or any terms or conditions herein, your sole remedy is to discontinue your use of the Service. Your continued use after a change to this Agreement has been posted constitutes your acceptance of this Agreement as modified by such changes.</p>
<h3><strong>Your Relationship with Us</strong></h3>
<p>Individuals who register as users of the Service ("Users") gain access to specific products and services offered by Youro, as well as those sold or provided by third-party medical providers, pharmacies, and other vendors through our Service. The Service facilitates access to prescription fulfillment services from various pharmacies (currently unspecified) and may include laboratory services from different laboratories (currently unspecified). Users acknowledge that their prescriptions may be handled and transferred among these unnamed Pharmacies. Additionally, the Service may introduce Users to various medical groups offering healthcare and/or urology services on the Platform (currently unspecified). These medical groups engage physicians, allied health professionals, and urology experts who provide healthcare and/or urology services through the Platform ("Providers"). Users recognize that any services received from these undisclosed Labs, Pharmacies, Medical Groups, or Providers through the Platform are subject to this Agreement, and these entities are considered third-party beneficiaries.</p>
<p>The practice of medicine or urology care by the Medical Groups or Providers is beyond our control. Each of these entities is solely responsible for directing medical care, urology care, and/or treatment. Users acknowledge that Youro is not a healthcare provider and that using the Service does not establish a doctor-patient or other health care provider-patient relationship with Youro. However, Users may enter into such relationships with the undisclosed Medical Group and/or Providers. The Labs and Pharmacies, each responsible for their professional services via the Service, are also beyond our control.</p>
<p>By agreeing to this Agreement, Users acknowledge that the Medical Group and/or Providers may communicate via the Service about diagnoses and/or treatments. Users understand that Youro is not accountable for the security or privacy of communication services used to receive such messages. It is the sole responsibility of Users to monitor and respond to these messages, with Youro, the Medical Group, or any Provider not held liable for any loss, injury, or claims resulting from Users' failure to engage with these communications or comply with treatment recommendations or instructions from the Medical Group or Providers.</p>
<p>While Users do not establish a doctor-patient or other health care provider-patient relationship with Youro, they establish a direct customer relationship to use the Service. This includes the purchase of non-prescription products or non-medical services directly from Youro via the Service. In this relationship, Users may provide personal information, including health information, subject to use by Youro in accordance with the Privacy Policy. Additional information is available in the "Privacy Policy" section and the "Protected Information" section below.</p>
<p><strong>Notice Regarding Your Financial Obligation for Services</strong></p>
<p>Youro and the Medical Groups are not affiliated with, and do not participate as providers in, any federal or state healthcare programs (e.g., Medicare, Medicaid) for the delivery of health care or urology services or supplies. Consequently, neither you nor Youro or the Medical Groups are eligible to receive payment from such programs for the services or products rendered through Youro or the Medical Groups. Additionally, in cases where Labs, Pharmacies, or Providers may be enrolled in federal or state healthcare programs, the manner in which services and products are provided or made accessible through the Service often precludes them from being recognized as covered benefits under these programs. By opting to utilize the Service, you explicitly opt to acquire products and services on a cash basis, independent of any federal or state healthcare program. Therefore, you bear sole responsibility for the costs associated with any service or product provided to you.</p>
<p>By consenting to use the Service, you acknowledge and affirm that (1) you are expressly opting to obtain products and services on a cash basis, unrelated to any federal or state healthcare program, and assume full financial responsibility for all services or products delivered to you through the Service; and (2) neither you nor Youro, the Labs, the Pharmacies, the Medical Groups, or the Providers will seek reimbursement from any federal or state healthcare program for the costs associated with the services and products provided to you through the Service.</p>
<p><strong>Subscription Products and Services</strong></p>
<p>Certain products and services offered for purchase through the Youro platform may necessitate acquiring them on a subscription basis that automatically renews. For such subscription-based offerings, your designated payment method will be charged at regular intervals, as detailed for the specific product or service during the checkout process. This automatic charging will persist until you opt to cancel your subscription. To ensure continuity in your treatment, the initial renewal may occur in advance. Subsequent charges and shipments might be processed up to two (2) days earlier on occasions such as holidays or for operational reasons.</p>
<p>We and/or the Providers may, at our discretion, reach out to you via the Youro platform periodically. These communications may aim to request updates to your information and facilitate ongoing subscriptions. You retain the option to cancel your subscription at any time by sending an email to support@youro.com, directly requesting cancellation, or managing the cancellation through your online account. The cancellation will become effective at the conclusion of the ongoing subscription period. Should you not cancel at least two (2) days before the upcoming renewal date, your subscription will automatically renew for another period. Refunds are not offered for partially used subscription periods, though exceptions may be considered on a case-by-case basis at our sole discretion. Additionally, we may provide the option to temporarily pause your subscription for a specified duration. Failure to cancel before the pause period concludes will result in the automatic resumption of charging to your designated payment method.</p>
<p>Subscription plans and prices may undergo adjustments over time; however, you will be notified in advance of any alterations to prices or changes in your subscription plans.</p>
<p>To streamline the user experience on the Youro platform, you will encounter and be obligated to pay a singular "total" subscription price. If a subscription product mandates a consultation with a Provider, incorporates a prescription product filled through one of the Pharmacies, and/or includes urology services, the total price encompasses charges for utilizing the Service, along with amounts charged by the Pharmacy for the prescription drug and the fee charged by the Medical Group for the services of the Provider, as applicable. These amounts are collected on behalf of and remitted to the Pharmacies and Medical Groups, respectively.</p>
<p><strong>Prescription Products</strong></p>
<p>Certain treatments offered through the Youro platform necessitate a valid prescription from a licensed urology provider. Access to prescription products is contingent upon completing a consultation with one of our Providers, who, upon deeming the prescription product suitable for you, will issue a prescription.</p>
<p>Upon the Provider's determination and prescription issuance, you will be provided information on options for filling the prescription. You will have to fill the prescription at any pharmacy of your choice, a choice prompted during your use of the Youro platform or by submitting a request to support@youro.com. Please note that prescriptions may be transferred among our partner Pharmacies without prior notice. It's important to be aware that not all prescriptions filled by the Pharmacies use child-resistant packaging, and your prescription product may not be dispensed in such a container.</p>
<p>Certain prescriptions may not be available through our partner Pharmacies and must be filled at a local pharmacy of your choice, as directed during your use of the Youro platform. This includes prescriptions used for various common primary care urology conditions.</p>
<p>If, following a consultation with a Provider, you opt to fill a prescription through one of our partner Pharmacies, the prescribed product will be shipped to you by the respective Pharmacy. The costs associated with the prescription are incorporated into the total amount charged to you by the Youro platform, as detailed in the "Subscription Products" section above. Alternatively, if you choose to fill the prescription at a pharmacy other than our partner Pharmacies, the Youro platform will transmit the prescription to your selected pharmacy. However, you are responsible for collecting or otherwise obtaining the prescription product and making direct payment to the pharmacy for the associated costs.</p>
<p>It's important to recognize that prescription products available through the Youro platform fall under the category of "Third-Party Goods and Services," as elucidated in the Third-Party Goods and Services section of this Agreement.</p>
<p><strong>Laboratory Products and Services</strong></p>
<p>Certain laboratory products and services accessible through the Youro platform, including at-home testing kits and services, necessitate a valid prescription or order from a licensed urology provider. Access to such laboratory services is contingent upon completing a consultation with one of our Providers, who, upon deeming the laboratory product and/or service suitable for you, will prescribe or order the necessary laboratory materials and services.</p>
<p>Laboratory products and services provided through the Youro platform are ordered and fulfilled both through our partner Labs and through local laboratories. If you receive laboratory products and/or services from a Lab through the Youro platform, the relevant testing materials will be shipped to you by the corresponding Lab. The costs associated with the laboratory products and services are integrated into the total amount charged to you by the Youro platform. If you choose to undergo the laboratory testing through the local laboratories, you are responsible for direct payment to the local laboratory for the associated costs.</p>
<p>It is essential to note that laboratory products and services accessible through the Youro platform fall under the category of "Third-Party Goods and Services," as explained in the Third-Party Goods and Services section of this Agreement.</p>
<p><strong>Limited Use and Availability</strong></p>
<p>The Youro platform is presently accessible solely to individuals situated in states where our services are offered, who are at least eighteen (18) years of age or older, or at least the age of majority in their jurisdiction of residence if higher than eighteen (18). By engaging with the Youro platform, you confirm and warrant that you are at least eighteen (18) years old or the age of majority in your jurisdiction, if higher than eighteen (18). Moreover, the Youro platform recognizes the importance of family involvement in healthcare decisions. As a registered user, you have the option to sign up family members, provided they are at least eighteen (18) years old. By initiating the sign-up process for a family member, you confirm that you have obtained explicit consent from the family member to access their medical and personal information for the purpose of facilitating their engagement with Youro's urological services. This ensures a collaborative and supportive approach to managing the healthcare needs of your family members through our platform.</p>
<p>Additionally, you affirm that, when using the Service for a consultation with a Provider, you are located in the same state as the shipping address provided in your account during the consultation. You agree to comply with all applicable laws in using the service and commit to using the Service for lawful purposes. It's important to note that the Youro platform is subject to state regulations, and service availability may evolve based on changes in regulatory requirements.</p>
<p>Certain products offered through the Service may be subject to additional age restrictions, and not all products or services are available to all age groups.</p>
<p>In specific situations, the Service may not be the most suitable channel for providing information to, communicating with, or seeking urological care and treatment from a healthcare provider. For example, certain medical conditions may necessitate in-person procedures or consultation with a healthcare provider other than your designated Provider. In such cases, you may receive a notification indicating that the Service is not applicable for the particular issue submitted, along with guidance on the next steps.</p>
<p><strong>Consent to Use of Telehealth Services</strong></p>
<p>The Youro platform employs telehealth to facilitate the delivery of urological care services through electronic communications, information technology, or other means, connecting patients with urology-trained providers remotely. While telehealth presents certain benefits, it is not a complete substitute for in-person care in every scenario. To access the Youro platform, users are required to carefully review and agree to an informed consent specifically addressing the use of telehealth, referred to as the "Patient Consent." This document will be provided through the platform, and users acknowledge that Youro is a third-party beneficiary of the Patient Consent, possessing the right to enforce it.</p>
<p><strong>Duty to Provide Information, Access, and Connectivity</strong></p>
<p>Users of the Youro platform bear the responsibility of providing and maintaining, at their own risk and expense, the necessary software and hardware capabilities as outlined in the platform's technical and quality requirements. This includes having a computer or mobile device equipped with a video camera and internet access. Users are also accountable for any associated fees, such as those for internet connection or mobile usage, incurred during platform access. Additionally, users are obligated to furnish truthful, accurate, and complete information in any forms or communications submitted through the platform. The platform reserves the right to modify access configurations, including software, hardware, or other requirements, with or without prior notice.</p>
<p><strong>Privacy Policy</strong></p>
<p>At Youro, we recognize the paramount importance of confidentiality and privacy concerning your personal information. Please refer to our Privacy Policy for a comprehensive description of how we collect, utilize, and disclose your personal information within the scope of our urological care platform.</p>
<p><strong>Protected Health Information</strong></p>
<p>When establishing an account with Youro, a direct customer relationship is formed, granting access to the various functions of the platform. Within this relationship, users provide information such as their name, email address, shipping details, and phone number to Youro. This information is collected, used, and disclosed in adherence to the Youro Privacy Policy and is not classified as "health" or "medical" information.</p>
<p>In certain instances while using specific components of the platform, users may also share medical information that falls under the purview of applicable laws. Youro does not operate as a "covered entity" under the Health Insurance Portability and Accountability Act of 1996 (HIPAA). It's pertinent to note that while state-specific privacy laws may apply, the mere involvement of health information does not automatically invoke HIPAA. Youro may, in some cases, be deemed a "business associate" of a Lab, Pharmacy, or Medical Group, potentially subjecting it to specific provisions of HIPAA related to "protected health information" (PHI) provided to the Labs, Pharmacies, or Medical Groups. Additionally, medical or health information subject to specific protections under state laws, collectively termed "Protected Information" along with PHI, will be handled in accordance with the respective laws. Any information not falling under the scope of Protected Information may be used or disclosed as outlined in the Youro Privacy Policy. It's important to clarify that de-identified information in compliance with HIPAA is excluded from the definition of Protected Information.</p>
<p>The Medical Groups and Providers on the Youro platform adhere to a Notice of Privacy Practices detailing the usage and disclosure of Protected Information. Users, by accessing or utilizing any part of the platform, acknowledge receipt of the Notice of Privacy Practices from their Medical Group and Provider(s).</p>
<p>By utilizing the Youro platform, users agree that even if HIPAA is applicable to Youro, Medical Groups, Providers, Labs, or Pharmacies, information submitted to Youro not exclusively intended for diagnosis, treatment, prescription fulfillment, or laboratory services is not considered Protected Information. Such information is subject to the Youro Privacy Policy and any applicable state laws governing its privacy and security.</p>
<p><strong>Registration; User Accounts, Passwords, and Security</strong></p>
<p>To gain access to the Youro platform and utilize its services, users are required to register and establish an account, which is exclusively accessible to registered users possessing usernames and passwords. Information provided during registration, such as name, username, email address, shipping details, and phone number, is distinct from Protected Information outlined in the relevant section above. Users commit to maintaining accurate and updated personal information provided to Youro, Medical Groups, Providers, Labs, or Pharmacies. Failure to adhere to this commitment, submission of untruthful, inaccurate, or incomplete information, or any reasonable suspicion of such actions grants Youro the right to suspend or terminate the user's account and service access. Users are obligated to promptly report any unauthorized use of their username, password, or any security breach related to the Service to Youro via email at [Youro support email]. Maintaining the confidentiality of login credentials is paramount, and Youro explicitly disclaims liability for losses arising from non-compliance with these terms. Usage of another user's account is strictly prohibited.</p>
<p>During the account creation process, users must provide a unique username and password for login purposes. To safeguard transmitted data's privacy through the Service, especially when personally identifiable information is involved, Youro employs encryption technology like Secure Sockets Layer (SSL). Additionally, measures are taken to secure User data against unauthorized access. However, users should be aware that the Service relies on software, hardware, and networks, which may, at times, require maintenance or experience issues beyond Youro's control. Users are responsible for logging out when not actively using their accounts, preventing unauthorized physical access to their devices, and ensuring the confidentiality of their login credentials.</p>
<p>Caution, good judgment, and sound sense should be exercised when using the Service. Users are expressly prohibited from attempting to violate the Service's security. Any such violations may result in criminal or civil penalties. Youro reserves the right to investigate suspected violations, and in case of criminal suspicion, may cooperate with law enforcement agencies in their investigations.</p>
<p><strong>Use and Ownership of the Youro Platform</strong></p>
<p>The Youro platform, along with the information and content it encompasses, is safeguarded by global copyright laws. In accordance with this agreement, Youro extends a limited, non-transferable, and revocable license to users for personal use of the platform. Unless specified otherwise in a separate license by Youro, the utilization of the platform or its content is governed by this agreement, with all rights reserved by Youro. You acknowledge that Youro and its suppliers retain complete rights, title, and interest in the platform, covering various elements such as computer code, themes, objects, photographs, product descriptions, blog posts, artwork, animations, sounds, musical compositions, audiovisual effects, methods of operation, moral rights, and documentation. Users are prohibited from altering, removing, or obscuring any copyright, trademark, service mark, or other proprietary rights notices associated with the platform. The stylized name of Youro and related graphics, logos, service marks, and trade names are the trademarks of Youro and require permission for use, including in connection with third-party products or services. Any other trademarks, service marks, or trade names visible on the platform belong to their respective owners.</p>
<p><strong>License to Information Submitted via the Youro Platform</strong></p>
<p>Except for Protected Information, any information transmitted to Youro through the platform, whether via direct entry, submission, email, or other means, is considered non-confidential and non-proprietary, subject to applicable law. Users, subject to selected account settings, grant Youro a fully paid, royalty-free, perpetual, irrevocable, worldwide, non-exclusive, and fully sublicensable license to use, license, distribute, reproduce, modify, adapt, publicly perform, and publicly display the submissions for the purpose of operating and providing the service. Users warrant that they have the necessary rights to grant this license. Users are responsible for their submissions, and Youro reserves the right to edit, duplicate, or alter submissions as deemed necessary. Users waive any moral rights and claim to compensation for such alterations. If a submission contains Protected Information, Youro's rights regarding its use or disclosure will be limited as per applicable law.</p>
<p><strong>Prohibited Use of the Youro Platform</strong></p>
<p>The use of the Youro platform is subject to certain restrictions, and you are expressly prohibited from engaging in or attempting the following actions:</p>
</div>
<div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Using the service for any unlawful, unauthorized, fraudulent, or malicious purpose.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Any activity that could damage, disable, overburden, or impair servers or connected networks.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Interfering with another party's use and enjoyment of the service.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Gaining unauthorized access to accounts, computer systems, or networks.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Accessing systems, data, or information not intended for user access.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Obtaining materials or information through unauthorized means.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Reverse engineering, disassembling, or decompiling any section or technology on the platform.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Using the service for purposes other than its intended business purpose.</p>
</div>
<div>
<p>Furthermore, in connection with your use of the Youro platform, you agree not to:</p>
<p>(a) Upload or transmit any content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, or inappropriate based on intrinsic characteristics.</p>
<p>(b) Create false identities or duplicative accounts for misleading purposes or impersonate any person or entity.</p>
<p>(c) Upload or transmit material without the right to reproduce, display, or transmit it.</p>
<p>(d) Upload files containing viruses, trojan horses, worms, or any other software that may damage the operation of another's computer.</p>
<p>(e) Delete author attributions, legal notices, or proprietary designations.</p>
<p>(f) Adversely affect the availability of resources to other users through excessive use of communication features.</p>
<p>(g) Upload unsolicited advertising, promotional materials, spam, chain letters, pyramid schemes, phishing, or any other form of solicitation.</p>
<p>(h) Violate any applicable local, state, national, or international law.</p>
<p>(i) Infringe on the proprietary rights of any party.</p>
<p>(j) Delete or revise material posted by others.</p>
<p>(k) Manipulate the display of the service through framing, mirroring, or similar navigational technology.</p>
<p>(l) Probe, scan, test the vulnerability of, or breach the authentication measures of the service.</p>
<p>(m) Register, subscribe, or attempt these actions on behalf of others without authorization.</p>
<p>(n) Harvest or collect information about others, including email addresses.</p>
<p>(o) Use automated or manual means to access the service without authorization.</p>
<p>(p) Assist or permit others to engage in any of these prohibited activities.</p>
<p>Youro reserves the right to take lawful actions in response to actual or suspected violations, including suspension or termination of a user's access and account. Cooperation with legal authorities and third parties in investigating suspected crimes or civil wrongs may occur. Youro retains the right to disclose information as deemed necessary to comply with applicable laws, regulations, legal processes, or governmental requests, or to edit, refuse to post, or remove information or materials in its sole discretion.</p>
<p><strong>Right to Monitor</strong></p>
<p>Youro reserves the right to monitor the general use of its platform at any time as it deems appropriate. It may remove any materials that, at its sole discretion, may be deemed illegal, subject Youro to liability, violate this agreement, or are inconsistent with Youro&rsquo;s purpose for the platform.</p>
<p><strong>Third-Party Offerings</strong></p>
<p>Within the Youro platform, various services or products are provided by entities other than Youro, including Labs, Pharmacies, Medical Groups, and Providers (collectively referred to as &ldquo;Third Parties&rdquo;). Additionally, Youro may present certain services, devices, items, or products from Third Parties for your purchase ("Third-Party Goods and Services"). Your interactions with Third Parties, including payment, delivery, and any associated terms, conditions, warranties, or representations, are solely between you and the Third Parties. It is your responsibility to conduct any necessary investigation before engaging in any transaction involving Third Parties or their offerings. Exercise caution, discretion, and good judgment when using the platform and disclosing personal information.</p>
<p>You acknowledge that Youro is not liable for any loss or damage resulting from your use of the platform, including Third-Party Goods and Services or interactions with Third Parties. In the event of a dispute with any Third Party or another user, Youro is not obligated to intervene, and you release and indemnify Youro, its associated entities, and their respective personnel from any claims or damages arising from such disputes or platform use. IF YOU ARE A CALIFORNIA RESIDENT, YOU WAIVE CALIFORNIA CIVIL CODE SECTION 1542, WHICH STATES: &ldquo;A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS THAT THE CREDITOR OR RELEASING PARTY DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE AND THAT, IF KNOWN BY HIM OR HER, WOULD HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR OR RELEASED PARTY.&rdquo;</p>
<p>It&rsquo;s important to note that certain Youro Owners and Personnel may have a financial interest in Third Parties and may benefit financially from your engagement with Third Parties and/or the purchase of Third-Party Goods and Services.</p>
<p><strong>Terms of Purchase</strong></p>
<p>All products presented for purchase on the Youro platform are subject to availability. We reserve the right to apply quantity limits to any order or reject all or part of an order without prior notice. In case of an error, we retain the right to rectify the mistake, adjust your order accordingly (including charging the correct price), or cancel the order and refund any amount charged. Product prices are subject to change, and you are responsible for applicable sales, use, duty, customs, or other governmental taxes ("Taxes") related to your purchase. We will collect Taxes if required and provide an estimate at checkout. The actual Taxes charged may vary due to factors such as tax rate changes.</p>
<p>Only valid payment methods acceptable to Youro can be used for purchases. You confirm that you are authorized to use your designated payment method. By placing an order, you authorize us to charge your payment method for the total order amount. If your payment method is declined, we will attempt to process the charge until approval. Your payment card information may be updated by our third-party payment service providers if your card has expired. We may use the updated information for future payments. You are responsible for any fees or charges applied by your bank or payment card issuer. In the event of a charge reversal, we may seek payment by an alternate method.</p>
<p>If any product in your order is unavailable, you will only be charged for the items included in the shipment. During a purchase, you may need to provide transaction-relevant information, and by doing so, you grant Youro the right to share such information with third parties (e.g., payment processors) to facilitate the transaction.</p>
<p>All monetary transactions on the Youro platform occur through the online payment processing application(s) provided by our third-party vendor, Stripe. Refer to Stripe's privacy policy and information security measures, available on their website, for additional details. The relationship with Stripe is contractual, and they operate independently of Youro's direction or control.</p>
<p>You are responsible for any shipping and handling charges indicated at the time of purchase. We may adjust these charges with notice. Delivery dates and times are estimates and not guaranteed. Risk of loss or damage to a product transfers to you upon delivery to our designated carrier.</p>
<p>We reserve the right to address user issues on an individual basis. In our sole discretion, we will resolve customer issues based on the specific circumstances. These rights extend to matters related to service termination.</p>
<p><strong>Termination</strong></p>
<p>Youro may terminate your access to the platform or any of its features or services at any time and for any reason without notice, including for conduct violating this agreement or discontinuation of the service. Provisions related to service security, prohibited activities, copyrights, trademarks, user submissions, disclaimers, limitation of liability, arbitration, resolution of disputes, indemnity, and jurisdictional issues shall survive termination. If your use is terminated, you agree not to attempt further use and indemnify Youro Parties for any liability incurred due to your violation of this restriction post-termination.</p>
<p>Except as specified in the Privacy Policy or as required by applicable law, we have no obligation, pre or post-termination, to return or provide Content, information you submitted, information from your Providers, or any other data related to you.</p>
<p><strong>Disclaimers</strong></p>
<p>Content and information on the Youro platform are provided for user convenience, and users who rely on such content do so at their own risk.</p>
<p>The service is offered on an "as is" or "as available" basis. User access or use of the service is voluntary and at their sole risk. Youro, along with third parties offering products or services through the service, including medical groups, providers, labs, and pharmacies, disclaims all warranties and conditions, express or implied, statutory or otherwise. This includes implied warranties of merchantability, non-infringement, satisfactory quality, and fitness for a particular purpose regarding the service and any information, content, products, services, or other material on the platform. Youro does not guarantee the accuracy, completeness, reliability, timeliness, or usefulness of the service. Youro does not warrant that the service will operate without delays, interruptions, interferences, imperfections, corruption, cyber attacks, viruses, malware, or any adverse incident.</p>
<p><strong>Limitation of Liability</strong></p>
<p>To the fullest extent permitted by applicable law, Youro shall not be liable to you or any other party for incidental, indirect, special, exemplary, and consequential damages, personal or bodily injury, emotional distress, wrongful death, loss of data, lost profits, or damages resulting from use or inability to use the service. This includes any information and content made available through the service or services/products offered by third parties. This applies whether based on warranty, contract, tort (including negligence), or any other legal theory, and whether or not Youro has been advised of the possibility of such damages. Youro's liability shall be limited to the extent of actual damages incurred by you, not to exceed U.S. $1,000.</p>
<p>Any claims arising from your use of the service must be brought within one (1) year of the event giving rise to such action.</p>
<p>Some jurisdictions may not allow the exclusion of certain warranties or the limitation/exclusion of liability for incidental or consequential damages. To the extent permitted, Youro's disclaimers and limitations of liability will apply with the minimum permitted under applicable law.</p>
<p><strong>Indemnification</strong></p>
<p>You agree to defend, indemnify, and hold Youro Parties and third parties providing products/services through the service (including medical groups, providers, labs, and pharmacies) harmless from suits, actions, claims, proceedings, damages, liabilities, losses, costs, and expenses arising from your use of the service, fraud, violation of law, or willful misconduct. We reserve the right to control the defense of any claim for which we are entitled to indemnification, and you agree to cooperate reasonably.</p>
<p><strong>Notices</strong></p>
<p>Youro may send notices to users via email, posted notices on the service, or regular mail, at its sole discretion.</p>
<p><strong>Electronic Communications</strong></p>
<p>By accessing or using the service or sending emails/SMS messages to Youro, medical groups, or providers, you consent to electronic communication. We may communicate with you via email, SMS, or through the service. You agree that electronically provided notices are considered given and received on the date transmitted, satisfying any legal requirements for written communication.</p>
<p><strong>Copyright</strong></p>
<p>Youro's policy is to cease the use of the platform by any user found to repeatedly infringe on copyright, upon receiving prompt notification from the copyright owner or their legal agent. If you believe that your work has been copied and posted on the Youro platform in a manner that constitutes copyright infringement, please provide our Copyright Agent with the following information: (1) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (2) a description of the copyrighted work that you claim has been infringed; (3) a description of the location on the platform of the material that you claim is infringing; (4) your address, telephone number, and email address; (5) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and (6) a statement by you, made under penalty of perjury, that the above information in your notice is accurate, and that you are the copyright owner or authorized to act on the copyright owner&rsquo;s behalf. Contact information for Youro's Copyright Agent for notice of claims of copyright infringement is as follows: legal@youro.com.</p>
<p><strong>Entire Agreement</strong></p>
<p>This Agreement and any other agreements Youro may post on the platform or that you and Youro may execute from time to time constitute the entire agreement between Youro and you in connection with your use of the platform. It supersedes any prior agreements between Youro and you regarding the use of the platform, including prior versions of this Agreement.</p>
<p><strong>Governing Law; Venue; Severability of Provisions</strong></p>
<p>This platform is controlled and operated by Youro. Individuals who opt to access the platform do so at their own initiative and are accountable for compliance with local laws, if and to the extent applicable. Access to the platform from jurisdictions where the contents of the platform are illegal or penalized is prohibited.</p>
<p>All parts of this Agreement apply to the maximum extent permitted by law. Our failure to enforce any provision of this Agreement will not constitute a waiver of such right. We both agree that if we cannot enforce a part of this Agreement as written, then that part will be replaced with terms that most closely match the intent of the unenforceable part to the extent permitted by law. Except as otherwise provided in this Agreement, the invalidity of part of this Agreement will not affect the validity and enforceability of the remaining provisions. The section headings are for convenience and do not have any force or effect.</p>
<p><strong>No Agency Relationship</strong></p>
<p>Neither this Agreement, nor any content, materials, or features of the platform create any partnership, joint venture, employment, or other agency relationship between you and Youro, the Medical Groups, the Providers, the Labs, or the Pharmacies. You may not enter into any contract on our behalf or bind us in any way.</p>
<p><strong>Assignment</strong></p>
<p>You may not assign any of your rights under this Agreement, and any such attempt will be null and void. Youro may, in its sole discretion, assign or transfer, without further consent or notification, this Agreement or any or all of the contractual rights and obligations pursuant to this Agreement, in whole or in part, to any affiliate of Youro or to a third party in the event that some or all of the business of Youro is transferred to such other third party by way of merger, sale of its assets or otherwise.</p>
<p><strong>Third-Party Beneficiaries</strong></p>
<p>Any use of third-party software provided in connection with the platform or any third-party goods and services accessed or used in connection with the platform will be governed by the applicable third-party&rsquo;s license or terms of use, if any, and if there is no such license or terms of use, by this Agreement. In addition to this Agreement, your use of the platform must comply with all applicable third-party terms of agreement, if any.</p>
<p>Except for the foregoing or as otherwise specifically set forth in this Agreement, including with respect to the indemnification obligations contained herein in favor of Youro, the Medical Groups, the Pharmacies, the Labs, and the Providers and the agreement to arbitration, we hereby expressly agree that there is no intent by either party to create or establish third-party beneficiary status rights or their equivalent in any other referenced individual, subcontractor, or third party, and, except as specifically set forth in this Agreement, that no third party shall have any right to enforce any right or enjoy any benefit that is created or established under this Agreement.</p>
<p><strong>Arbitration Agreement / Class Waiver</strong></p>
<p>You and we mutually agree that any legal claim, dispute, or other controversy between you and us or any of the Youro entities, any medical groups, providers, labs, or pharmacies arising out of or related in any way to the Youro entities, the platform, the content, or the service, or any other goods, services, or advertising by Youro or any of the Youro entities, labs, pharmacies, medical groups, or providers, including controversies relating to the applicability, enforceability, or validity of any provision of this agreement (collectively, "disputes"), that is not resolved by an informal dispute resolution conference (as defined and described below), shall be resolved in confidential binding arbitration conducted before one commercial arbitrator from the American Arbitration Association ("AAA"), rather than in a court, as described herein. The arbitration will be governed by the AAA&rsquo;s Consumer Arbitration Rules and, if the arbitrator deems them applicable, the Supplementary Procedures for Consumer-Related Disputes (collectively, "Rules and Procedures"). You acknowledge that you are voluntarily and knowingly forfeiting your right to a trial by jury and to otherwise proceed in a lawsuit in state or federal court, except as expressly provided herein. For the purposes of this arbitration agreement, "dispute" will also include disputes that arose or involve facts occurring before the existence of this or any prior versions of the terms and conditions, as well as claims that may arise after the termination of these terms and conditions.</p>
<p>In the event a dispute arises between us, we are committed to working with you to reach a reasonable resolution. You and we agree that good-faith informal efforts to resolve disputes can result in a prompt, low‐cost, and mutually beneficial outcome. You and we, therefore, agree that before either party commences arbitration against the other (or initiates an action in small claims court if a party so elects), we will personally meet and confer telephonically or via video conference, in a good-faith effort to resolve informally any dispute covered by this Arbitration Agreement (&ldquo;Informal Dispute Resolution Conference&rdquo;). If you are represented by counsel, your counsel may participate in the conference, but you will also participate in the conference.</p>
<p>Before you commence arbitration of a dispute, you must provide us with a written Notice of Dispute that includes your name, residence address, username (if applicable), and email address associated with your user account (if applicable), a detailed description of the dispute, and the relief you seek. Before we commence arbitration of a dispute against you, we will provide a written Notice of Dispute to you with a detailed description of the dispute and the relief we seek. Any Notice of Dispute you send to us should be mailed to Youro Health, Inc., [Your Address], ATTN: Dispute Notice. Notwithstanding anything to the contrary in this Agreement, if we make any future material modification to any provisions of this Agreement that govern the arbitration or resolution of disputes, such changes will not apply to any dispute between you and us for which either party had previously provided a written Notice of Dispute to the other in accordance with this paragraph. Further, if we make any future material changes to the provisions of this Agreement that govern the arbitration or resolution of disputes, you may reject such changes by sending a written notice of your rejection decision to us at Youro Health, Inc., [Your Address], ATTN: Arbitration Opt-Out within 30 days of the effective date of such modifications. Changes to this Arbitration Agreement do not provide you with a new opportunity to opt out of the Arbitration Agreement if you have previously agreed to a version of these Terms and Conditions and did not validly opt out of arbitration. If you reject any change or update to this Arbitration Agreement, and you were bound by an existing agreement to arbitrate disputes, the provisions of this Arbitration Agreement as of the date you first accepted the Terms and Conditions (or accepted any subsequent changes to these Terms and Conditions) remain in full force and effect. We will continue to honor any valid opt-outs of the Arbitration Agreement that you made to a prior version of these Terms and Conditions.</p>
<p>Except as provided above, if any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable, then such specific part or parts shall be of no force and effect and shall be severed, and the remainder of the Arbitration Agreement shall continue in full force and effect.</p>
<p><strong>Contacting Us</strong></p>
<p>If you have any questions or concerns about this Agreement, please contact us by email at support@youro.com. We will attempt to respond to your questions or concerns promptly after we receive them.</p>
</div>

        </>
    )
}

export default Terms;